apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clonebuildpushrun-
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: clonebuildpush
  podTemplate:
    securityContext:
      fsGroup: 65532  
  params:
    - name: revision
      value: main
    - name: gitrepositoryurl
      value: "https://github.com/blinovmaksym/Wordpress-Tekton-atK8s-inGCP"
    - name: IMAGE
      value: "docker.io/maksymblinov/init_db_wp"
    - name: TAG
      value: v1
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi   